name: Sync Dantotsu to Codeberg and GitLab

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rebelonion/Dantotsu
        run: |
          git clone --branch dev https://git.rebelonion.dev/rebelonion/Dantotsu.git .
          git fetch origin dev
          git checkout dev

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH for Codeberg and GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa codeberg.org >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts

      - name: Prepare and push to Codeberg
        run: |
          git remote add codeberg git@codeberg.org:itsmechinmoy/Dantotsu.git
          git rm -f .github/workflows/codeberg-gitlab-sync.yml || echo "File not present, continuing"
          git commit -m "Remove workflow file for Codeberg sync" || echo "No changes to commit"
          git push codeberg dev --force

      - name: Prepare and push to GitLab
        run: |
          git remote add gitlab git@gitlab.com:itsmechinmoy/dantotsu.git
          git rm -f .github/workflows/codeberg-gitlab-sync.yml || echo "File not present, continuing"
          git commit -m "Remove workflow file for GitLab sync" || echo "No changes to commit"
          git push gitlab dev --force
