name: Sync Self-host Dantotsu to GitHub

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rebelonion/Dantotsu
        run: |
          git clone --branch dev https://git.rebelonion.dev/rebelonion/Dantotsu.git .
          git fetch origin dev
          git checkout dev

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          ssh -T git@github.com | grep "Hi itsmechinmoy/Dantotsu" && echo "SSH connection successful" || { echo "SSH connection failed"; exit 1; }

      - name: Prepare and push to GitHub
        run: |
          git remote add github git@github.com:itsmechinmoy/Dantotsu.git || echo "Remote already exists"
          git fetch github
          git checkout -B main
          git rm -f .github/workflows/sync-to-github.yml || echo "File not present, continuing"
          git commit -m "Sync from rebelonion/Dantotsu dev branch" || echo "No changes to commit"
          git push github main --force
