name: Sync Self-host Dantotsu to GitHub

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rebelonion/Dantotsu
        run: |
          git clone --branch dev https://git.rebelonion.dev/rebelonion/Dantotsu.git .
          git fetch origin dev
          git checkout dev

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare and push to GitHub
        env:
          GITHUB_PAT: ${{ secrets.DANTOTSU_SYNC }}
        run: |
          git remote add github https://$GITHUB_PAT@github.com/itsmechinmoy/Dantotsu.git || echo "Remote already exists"
          git fetch github
          git checkout -B main
          git rm -f .github/workflows/sync-to-github.yml || echo "File not present, continuing"
          git commit -m "Sync from rebelonion/Dantotsu dev branch" || echo "No changes to commit"
          git push github main --force
