name: Sync Dantotsu to GitHub

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rebelonion/Dantotsu
        run: |
          git clone --branch dev https://git.rebelonion.dev/rebelonion/Dantotsu.git .
          git fetch origin dev
          git checkout dev

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Prepare and push to GitHub
        run: |
          git remote add github git@github.com:itsmechinmoy/Dantotsu.git
          git rm -f .github/workflows/rebeloniondantotsu-itsmechinmoydantotsu_sync.yml || echo "File not present, continuing"
          git commit -m "Remove workflow file for GitHub sync" || echo "No changes to commit"
          git push github dev --force
