name: Update Release Notes with Download Badges

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout itsmechinmoy/echo
        uses: actions/checkout@v4
        with:
          repository: itsmechinmoy/echo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all releases
        id: fetch-releases
        run: |
          echo "Fetching all releases from itsmechinmoy/echo"
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                         -H "Accept: application/vnd.github+json" \
                         https://api.github.com/repos/itsmechinmoy/echo/releases)
          echo "$RESPONSE" > releases.json
          echo "RELEASE_COUNT=$(jq length releases.json)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update release notes with download badges
        run: |
          RELEASE_COUNT=$(jq length releases.json)
          if [ "$RELEASE_COUNT" -eq 0 ]; then
            echo "No releases found!"
            exit 0
          fi
          jq -c '.[]' releases.json | while read -r release; do
            TAG_NAME=$(echo "$release" | jq -r '.tag_name')
            RELEASE_ID=$(echo "$release" | jq -r '.id')
            CURRENT_BODY=$(echo "$release" | jq -r '.body')
            # Check if badges already exist to avoid duplication
            if echo "$CURRENT_BODY" | grep -q "img.*github/downloads/itsmechinmoy/echo"; then
              echo "Badges already present in release $TAG_NAME, skipping update."
              continue
            fi
            # Prepare updated body with download badges
            echo -e "$CURRENT_BODY\n\n---\n### Download Counts\n<img src=\"https://img.shields.io/github/downloads/itsmechinmoy/echo/total?style=for-the-badge&label=TOTAL%20DOWNLOADS&labelColor=black&color=white\"/>\n<img src=\"https://img.shields.io/github/downloads/itsmechinmoy/echo/$TAG_NAME/total?style=for-the-badge&label=CURRENT%20RELEASE&labelColor=black&color=white\"/>" > updated_body.txt
            # Update the release note
            curl -s -X PATCH \
                 -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 -d "{\"body\": $(jq -s -R . updated_body.txt)}" \
                 https://api.github.com/repos/itsmechinmoy/echo/releases/$RELEASE_ID
            echo "Updated release note for tag $TAG_NAME"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
